### ISSUE TITLE
iPad & iPhone compatibility

### ISSUE THREAD

**Issue by micheldlebeau** [darsain/motio#5]
I have a vertical sprite which looks good on my computer, nexus 4, nexus 7, but on iPad and iPhone it appears like shown below:
![photo](https://f.cloud.github.com/assets/4929708/742767/3b8d95ae-e3d5-11e2-8588-aaac06ca7b87.png)

**Comment by darsain** [comment]
All the motio does is just increments the background position. In sprite animation mode, it increments by `frameSize`, i.e. width (or height in vertical sprites) of the frame. In panning mode, it increments by `speedX` and `speedY` value per second.

Motio does nothing to your styling. It touches only `background-position`. So what you see is probably due to other styles applied to the frame.

That's about all I can guess by having no isolated case, or code, but only a brief screenshot...

**Comment by micheldlebeau** [comment]
You are right, I didn't provide much. Here is the code
HTML

``` html
<div id="sprite" class="sprite" style="max-width: 960px; height: 275px; margin-bottom: 15px; margin-top: -20px; width: 100%; border-radius: 5px 5px 5px 5px; ">
    <img src="http://wavelengthpr.com.au/wordpress/wp-content/uploads/2013/05/about_00000.jpg" id="imgLoad">
</div>
```

CSS (during the animation, I tried to fix the problem with the CSS applied to #sprite, without success)

``` CSS
element.style {
    background-image: url("http://wavelengthpr.com.au/wordpress/wp-content/uploads/2013/05/Untitled-1.jpg");
    background-position: 0 -10725px;
    border-radius: 5px 5px 5px 5px;
    height: 275px;
    margin-bottom: 15px;
    margin-top: -20px;
    max-width: 960px;
    width: 100%;
}
#sprite {
    background-repeat: no-repeat;
    background-size: 100% auto;
}
```

JavaScript

``` javascript
var bgImg = new Image();
bgImg.onload = function(){
   document.getElementById('sprite').style.backgroundImage = 'url(' + bgImg.src + ')';
   var sprite = new Motio(document.getElementById('sprite'), {
    fps: 12,
    vertical: 1,
    frames: 44 
});
sprite.play(); // Start playing animation
document.getElementById('sprite').removeChild(document.getElementById('sprite').getElementsByTagName("img")[0]);
};
bgImg.src = "http://wavelengthpr.com.au/wordpress/wp-content/uploads/2013/05/Untitled-1.jpg";
```

**Comment by darsain** [comment]
You don't need to wait for any load events for background images. 90% of the code you posted is redundant. All you need is an element with a needed sprite as its CSS background, and to call a `new Motio` on it.

HTML:

``` html
<div class="animation"></div>
```

CSS:

``` css
.animation {
  background: url('path/to/sprite.jpg');
}
```

JS:

``` js
new Motio(document.querySelector('.animation'), {
  fps: 12,
  vertical: 1,
  frames: 44
}).play();

// Or with jQuery
$('.animation').motio({
  fps: 12,
  vertical: 1,
  frames: 44
});
```

Motio assumes that one frame has the same dimensions as the `.animation` element containing it. If that is not the case, you can use `width` & `height` options to specify the exact size of one frame. For more detailed description, see the [Options documentation page](https://github.com/Darsain/motio/wiki/Options).

The markup and styling details can be found in [Markup documentation page](https://github.com/Darsain/motio/wiki/Markup).

And overall, [RTFM](https://github.com/Darsain/motio/wiki) :)

---

Regarding your problem, due to a lot of devices having higher pixel densities, and `%` values may be inconsistent between devices (dunno for sure), try removing this line:

``` css
background-size: 100% auto;
```

Basically you need to have a correct styling and dimensions in place. I made it to be as straight forward as possible: sprite with frames should be used as a CSS background for an element, which in turn should have the exact dimensions of one animation frame.

![Sprite markup](http://i.imgur.com/Sazfe0Q.png)

So if you have a vertical sprite with 10 frames that is 100px &times; 1000px big, the frame should be 100px &times; 100px big to contain one frame. If the size of one frame doesn't match the size of the element, you'll get what you have described above.

The size of one frame is controlled by the size of an image and CSS background styling applied to the element, all of which is controlled by you, and not touched by Motio. Again, all the Motio does is adjust the `background-position` property.

I'm closing this as this is not an issue with Motio, but rather your unfortunate implementation/styling.
